name=Hyperwisor-IOT
version=1.0.0
author=NIKOLAINDUSTRY
maintainer=NIKOLAINDUSTRY <support@nikolaindustry.com>
sentence=A powerful abstraction layer for ESP32-based IoT devices.
paragraph=Handles Wi-Fi provisioning, real-time communication via nikolaindustry-realtime, OTA updates, GPIO management, and structured JSON command execution out of the box.
category=Communication
url=https://github.com/nikolaindustry/hyperwisor-iot-arduino-library
architectures=esp32
depends=ArduinoJson,WebSockets
